version: "3.3"
services:
  broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883" # MQTT Port
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "test"]
      interval: 10s
      timeout: 5s
      retries: 3

  subscriber:
    build:
      context: ./subscriber
      dockerfile: ../Dockerfile
    container_name: mqtt-subscriber
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - BROKER=broker
      - TOPIC=sensor/data
    command: ["python", "sub.py"]

  publisher:
    build:
      context: ./publisher
      dockerfile: ../Dockerfile
    container_name: mqtt-publisher
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - BROKER=broker
      - TOPIC=sensor/data
    command: ["python", "pub.py"]
